// Application Configuration & Limits
export const APP_CONFIG = {
  SITE_PASSCODE: (typeof import.meta !== 'undefined' && import.meta.env?.VITE_SITE_PASSCODE) || '7940',
  MAX_FILE_SIZE_MB: Number(typeof import.meta !== 'undefined' && import.meta.env?.VITE_MAX_FILE_SIZE_MB) || 100,
  MAX_DURATION_SEC: Number(typeof import.meta !== 'undefined' && import.meta.env?.VITE_MAX_DURATION_SEC) || 300, // 5 minutes
  APP_TITLE: (typeof import.meta !== 'undefined' && import.meta.env?.VITE_APP_TITLE) || 'ZEN CAPTION AI STUDIO'
};

// Available Fonts (Local system & web-safe creative fonts)
export const FONTS = [
  { id: 'PlayfairDisplay', name: 'Playfair Display (Luxury Editorial)', family: "'Playfair Display', Georgia, serif" },
  { id: 'BodoniModa', name: 'Bodoni Moda (Vogue Runway Luxury)', family: "'Bodoni Moda', Georgia, serif" },
  { id: 'Cinzel', name: 'Cinzel (Classical Roman Serif)', family: "'Cinzel', serif" },
  { id: 'Syne', name: 'Syne (Viral Ultra Display)', family: "'Syne', sans-serif" },
  { id: 'Righteous', name: 'Righteous (Bold Rounded Retro)', family: "'Righteous', cursive, sans-serif" },
  { id: 'PlusJakartaSans', name: 'Plus Jakarta Sans (Viral Clean)', family: "'Plus Jakarta Sans', sans-serif" },
  { id: 'Anton', name: 'Anton (Heavy Poster Impact)', family: "'Anton', sans-serif" },
  { id: 'Bungee', name: 'Bungee (Urban Block Display)', family: "'Bungee', cursive, sans-serif" },
  { id: 'Inter', name: 'Inter (Modern Sans)', family: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif" },
  { id: 'Montserrat', name: 'Montserrat (Bold Clean)', family: "'Montserrat', sans-serif" },
  { id: 'Roboto', name: 'Roboto (Universal)', family: "'Roboto', sans-serif" },
  { id: 'Impact', name: 'Impact (Viral Meme / TikTok)', family: "Impact, 'Arial Black', sans-serif" },
  { id: 'BebasNeue', name: 'Bebas Neue (Cinematic Tall)', family: "'Bebas Neue', Impact, sans-serif" },
  { id: 'Oswald', name: 'Oswald (Punchy Bold)', family: "'Oswald', sans-serif" },
  { id: 'Outfit', name: 'Outfit (Futuristic Tech)', family: "'Outfit', sans-serif" },
  { id: 'Bangers', name: 'Bangers (Comic / Dynamic)', family: "'Bangers', cursive, Impact" },
  { id: 'CourierNew', name: 'Courier New (Terminal Typewriter)', family: "'Courier New', monospace" },
  { id: 'Arial', name: 'Arial (Common Clean)', family: "Arial, Helvetica, sans-serif" }
];

// 9 Caption Positions on the video (Complete 3x3 Matrix)
export const CAPTION_POSITIONS = [
  { id: 'top', label: 'Top', x: '50%', y: '14%', align: 'center', transform: 'translate(-50%, -50%)' },
  { id: 'bottom', label: 'Bottom', x: '50%', y: '82%', align: 'center', transform: 'translate(-50%, -50%)' },
  { id: 'middle', label: 'Middle', x: '50%', y: '50%', align: 'center', transform: 'translate(-50%, -50%)' },
  { id: 'middle-left', label: 'Middle Left', x: '6%', y: '50%', align: 'left', transform: 'translate(0, -50%)' },
  { id: 'middle-right', label: 'Middle Right', x: '94%', y: '50%', align: 'right', transform: 'translate(-100%, -50%)' },
  { id: 'top-left', label: 'Top Left', x: '6%', y: '14%', align: 'left', transform: 'translate(0, -50%)' },
  { id: 'top-right', label: 'Top Right', x: '94%', y: '14%', align: 'right', transform: 'translate(-100%, -50%)' },
  { id: 'bottom-left', label: 'Bottom Left', x: '6%', y: '82%', align: 'left', transform: 'translate(0, -50%)' },
  { id: 'bottom-right', label: 'Bottom Right', x: '94%', y: '82%', align: 'right', transform: 'translate(-100%, -50%)' }
];

// 22+ Caption Animation Styles
export const CAPTION_ANIMATIONS = [
  { id: 'anim-3d-tilt', name: '3D Tilt & Spring', description: 'Dynamic 3D perspective swing with spring recoil', cssClass: 'anim-3d-tilt' },
  { id: 'anim-neon-shimmer', name: 'Neon Shimmer Sweep', description: 'Luminous light beam scanning across words', cssClass: 'anim-neon-shimmer' },
  { id: 'anim-bounce-drop', name: 'Kinetic Bounce Drop', description: 'Falling from above with elastic rubber bounce', cssClass: 'anim-bounce-drop' },
  { id: 'anim-cinematic-drift', name: 'Cinematic Drift', description: 'Anti-gravity floating zero-g sway', cssClass: 'anim-cinematic-drift' },
  { id: 'anim-elastic-snap', name: 'Elastic Magnetic Snap', description: 'Dramatic oversize zoom snap into place', cssClass: 'anim-elastic-snap' },
  { id: 'anim-liquid-gradient', name: 'Holo Liquid Flow', description: 'Rotating holographic rainbow gradient flow', cssClass: 'anim-liquid-gradient' },
  { id: 'anim-fire-flare', name: 'Solar Flare Pulse', description: 'Energetic warm flare burst with heatwave blur', cssClass: 'anim-fire-flare' },
  { id: 'anim-left-right', name: 'Left to Right', description: 'Smooth slide-in from left', cssClass: 'anim-slide-left-right' },
  { id: 'anim-right-left', name: 'Right to Left', description: 'Smooth slide-in from right', cssClass: 'anim-slide-right-left' },
  { id: 'anim-top-bottom', name: 'Top to Bottom', description: 'Descend smoothly into frame', cssClass: 'anim-slide-top-bottom' },
  { id: 'anim-bottom-top', name: 'Bottom to Top', description: 'Ascend punchy from bottom', cssClass: 'anim-slide-bottom-top' },
  { id: 'anim-blink', name: 'Blink / Flash', description: 'Attention-grabbing double flash', cssClass: 'anim-blink' },
  { id: 'anim-typewriter', name: 'Typewriter', description: 'Word by word typewriter reveal', cssClass: 'anim-typewriter' },
  { id: 'anim-pop', name: 'Pop / Scale Bounce', description: 'Viral TikTok / Reels bouncy pop', cssClass: 'anim-pop' },
  { id: 'anim-karaoke-glow', name: 'Karaoke Glow', description: 'Active word neon highlighter', cssClass: 'anim-karaoke-glow' },
  { id: 'anim-wave', name: 'Wave / Bob', description: 'Gentle harmonic text wave', cssClass: 'anim-wave' },
  { id: 'anim-fade', name: 'Smooth Fade', description: 'Cinematic subtle dissolve', cssClass: 'anim-fade' },
  { id: 'anim-blur', name: 'Blur Unveil', description: 'Optic defocus into sharp focus', cssClass: 'anim-blur' },
  { id: 'anim-neon-pulse', name: 'Neon Pulse', description: 'Cyberpunk oscillating light emission', cssClass: 'anim-neon-pulse' },
  { id: 'anim-glitch', name: 'Glitch Cyber', description: 'Digital chromatic glitch twitch', cssClass: 'anim-glitch' },
  { id: 'anim-flip3d', name: '3D Flip In', description: 'Tumbling 3D perspective rotation', cssClass: 'anim-flip3d' },
  { id: 'anim-zoom-impact', name: 'Zoom Impact', description: 'Sudden explosive scale punch', cssClass: 'anim-zoom-impact' }
];

// 16 Production-Ready Caption Templates with Unique Scopes
export const CAPTION_TEMPLATES = [
  {
    id: 'september-pop',
    name: 'September Vibrant Pop',
    scope: 'Gen-Z lifestyle, shopping hauls, dating stories. Playful rounded typography with electric neon pink accents.',
    category: 'viral',
    icon: '💖',
    badge: 'DEFAULT / POP',
    previewBg: '#000000',
    sampleNormal: 'for',
    sampleProminent: 'September',
    config: {
      templateId: 'september-pop',
      normalFontFamily: 'Outfit',
      prominentFontFamily: 'Righteous',
      fontSize: 28,
      position: 'middle-left',
      textColor: '#FFFFFF',
      prominentColor: '#FF4DA6',
      normalOutlineColor: '#000000',
      normalOutlineWidth: 2.0,
      prominentOutlineColor: '#000000',
      prominentOutlineWidth: 3.5,
      shadowColor: 'rgba(0,0,0,0.95)',
      shadowBlur: 10,
      animation: 'anim-bounce-drop',
      uppercase: false,
      karaokeHighlightColor: '#FF4DA6',
      enableLastWordColor: true,
      lastWordColor: '#FF4DA6'
    }
  },
  {
    id: 'viral-reel',
    name: 'Viral Reel (Hormozi / Ref)',
    scope: 'TikTok & Reels viral engagement. Bold clean normal words with electric yellow & cyan hero accents.',
    category: 'viral',
    icon: '🔥',
    badge: 'HORMOZI VIRAL',
    previewBg: '#000000',
    sampleNormal: 'result of',
    sampleProminent: 'Zen AI',
    config: {
      templateId: 'viral-reel',
      normalFontFamily: 'Inter',
      prominentFontFamily: 'Syne',
      fontSize: 32,
      position: 'middle-left',
      textColor: '#FFFFFF',
      prominentColor: '#FFE600',
      normalOutlineColor: '#000000',
      normalOutlineWidth: 2.5,
      prominentOutlineColor: '#000000',
      prominentOutlineWidth: 3.5,
      shadowColor: 'rgba(0,0,0,0.95)',
      shadowBlur: 10,
      animation: 'anim-pop',
      uppercase: false,
      karaokeHighlightColor: '#00F0FF',
      enableLastWordColor: true,
      lastWordColor: '#FFE600'
    }
  },
  {
    id: 'emily-luxury',
    name: 'Emily Luxury Vogue',
    scope: 'Fashion runways, luxury lifestyle, aesthetics & perfume vlogs. Refined classical serif with soft rose-gold glow.',
    category: 'luxury',
    icon: '✨',
    badge: 'LUXURY SERIF',
    previewBg: '#000000',
    sampleNormal: 'this is',
    sampleProminent: 'Emily',
    config: {
      templateId: 'emily-luxury',
      normalFontFamily: 'Inter',
      prominentFontFamily: 'PlayfairDisplay',
      fontSize: 30,
      position: 'middle-left',
      textColor: '#FFFFFF',
      prominentColor: '#FFB6C1',
      normalOutlineColor: '#000000',
      normalOutlineWidth: 1.5,
      prominentOutlineColor: '#000000',
      prominentOutlineWidth: 2.0,
      shadowColor: 'rgba(0,0,0,0.85)',
      shadowBlur: 8,
      animation: 'anim-fade',
      uppercase: false,
      karaokeHighlightColor: '#FFB6C1',
      enableLastWordColor: false
    }
  },
  {
    id: 'cyberpunk-neon',
    name: 'Cyberpunk Neon Beast',
    scope: 'Gaming clips, AI tech showcases, futuristic tutorials. High-voltage cyan light sweeps with deep neon shadows.',
    category: 'tech',
    icon: '⚡',
    badge: 'CYBER TECH',
    previewBg: '#000000',
    sampleNormal: 'neural',
    sampleProminent: 'Cyber 2077',
    config: {
      templateId: 'cyberpunk-neon',
      normalFontFamily: 'PlusJakartaSans',
      prominentFontFamily: 'Syne',
      fontSize: 34,
      position: 'middle-left',
      textColor: '#FFFFFF',
      prominentColor: '#00F0FF',
      normalOutlineColor: '#001A26',
      normalOutlineWidth: 2.0,
      prominentOutlineColor: '#001A26',
      prominentOutlineWidth: 3.0,
      shadowColor: 'rgba(0,240,255,0.4)',
      shadowBlur: 14,
      animation: 'anim-neon-shimmer',
      uppercase: false,
      karaokeHighlightColor: '#00F0FF',
      enableLastWordColor: true,
      lastWordColor: '#00F0FF'
    }
  },
  {
    id: 'cinematic-drama',
    name: 'Cinematic Drama',
    scope: 'Movie essays, historical documentaries, deep storytelling. Regal Roman serif with polished metallic gold accents.',
    category: 'cinema',
    icon: '🎬',
    badge: 'CINEMATIC',
    previewBg: '#000000',
    sampleNormal: 'cinematic',
    sampleProminent: 'Drama',
    config: {
      templateId: 'cinematic-drama',
      normalFontFamily: 'Cinzel',
      prominentFontFamily: 'BodoniModa',
      fontSize: 28,
      position: 'middle-left',
      textColor: '#F5F5F0',
      prominentColor: '#FFD700',
      normalOutlineColor: '#1A1A1A',
      normalOutlineWidth: 1.5,
      prominentOutlineColor: '#1A1A1A',
      prominentOutlineWidth: 2.5,
      shadowColor: 'rgba(0,0,0,0.9)',
      shadowBlur: 12,
      animation: 'anim-cinematic-drift',
      uppercase: false,
      karaokeHighlightColor: '#FFD700',
      enableLastWordColor: false
    }
  },
  {
    id: 'finance-alpha',
    name: 'Finance & Crypto Alpha',
    scope: 'Stock market, real estate, crypto advice, money podcasts. Solid editorial clean sans with emerald profit green accents.',
    category: 'business',
    icon: '📈',
    badge: 'FINANCE & BIZ',
    previewBg: '#000000',
    sampleNormal: 'market',
    sampleProminent: 'Alpha 100x',
    config: {
      templateId: 'finance-alpha',
      normalFontFamily: 'PlusJakartaSans',
      prominentFontFamily: 'Oswald',
      fontSize: 32,
      position: 'middle-left',
      textColor: '#FFFFFF',
      prominentColor: '#10B981',
      normalOutlineColor: '#000000',
      normalOutlineWidth: 2.5,
      prominentOutlineColor: '#000000',
      prominentOutlineWidth: 3.0,
      shadowColor: 'rgba(0,0,0,0.9)',
      shadowBlur: 8,
      animation: 'anim-pop',
      uppercase: false,
      karaokeHighlightColor: '#10B981',
      enableLastWordColor: true,
      lastWordColor: '#10B981'
    }
  },
  {
    id: 'comic-pop-art',
    name: 'Comic Pop Action',
    scope: 'Gaming fails, comedy sketches, animation commentary. Punchy comic book style with crimson borders and 3D bounce.',
    category: 'entertainment',
    icon: '💥',
    badge: 'COMIC BOOK',
    previewBg: '#000000',
    sampleNormal: 'action',
    sampleProminent: 'BOOM!',
    config: {
      templateId: 'comic-pop-art',
      normalFontFamily: 'Bangers',
      prominentFontFamily: 'Bangers',
      fontSize: 36,
      position: 'middle-left',
      textColor: '#FFFFFF',
      prominentColor: '#FFE600',
      normalOutlineColor: '#FF0000',
      normalOutlineWidth: 3.0,
      prominentOutlineColor: '#FF0000',
      prominentOutlineWidth: 4.0,
      shadowColor: 'rgba(0,0,0,0.9)',
      shadowBlur: 10,
      animation: 'anim-3d-tilt',
      uppercase: true,
      karaokeHighlightColor: '#FFE600',
      enableLastWordColor: true,
      lastWordColor: '#FFE600'
    }
  },
  {
    id: 'midnight-minimalist',
    name: 'Midnight Minimalist',
    scope: 'Architecture, silent vlogs, coding timelapses, philosophy. Pure understated elegance with pristine clean contrast.',
    category: 'minimal',
    icon: '🌙',
    badge: 'MINIMALIST',
    previewBg: '#000000',
    sampleNormal: 'pure',
    sampleProminent: 'Minimal',
    config: {
      templateId: 'midnight-minimalist',
      normalFontFamily: 'Inter',
      prominentFontFamily: 'Inter',
      fontSize: 26,
      position: 'middle-left',
      textColor: '#FFFFFF',
      prominentColor: '#E2E8F0',
      normalOutlineColor: 'transparent',
      normalOutlineWidth: 0,
      prominentOutlineColor: 'transparent',
      prominentOutlineWidth: 0,
      shadowColor: 'rgba(0,0,0,0.85)',
      shadowBlur: 12,
      animation: 'anim-fade',
      uppercase: false,
      karaokeHighlightColor: '#FFFFFF',
      enableLastWordColor: false
    }
  },
  {
    id: 'karaoke-spotlight',
    name: 'Karaoke Spotlight',
    scope: 'Singing, lip-sync, podcast hooks, high-energy speech. Dynamic word-by-word active spotlight karaoke highlighting.',
    category: 'music',
    icon: '🎤',
    badge: 'KARAOKE LIVE',
    previewBg: '#000000',
    sampleNormal: 'live',
    sampleProminent: 'Spotlight',
    config: {
      templateId: 'karaoke-spotlight',
      normalFontFamily: 'Montserrat',
      prominentFontFamily: 'Montserrat',
      fontSize: 32,
      position: 'middle-left',
      textColor: '#D1D5DB',
      prominentColor: '#00F0FF',
      normalOutlineColor: '#000000',
      normalOutlineWidth: 2.0,
      prominentOutlineColor: '#000000',
      prominentOutlineWidth: 2.5,
      shadowColor: 'rgba(0,0,0,0.9)',
      shadowBlur: 8,
      animation: 'anim-karaoke-glow',
      uppercase: false,
      karaokeHighlightColor: '#FF007A',
      enableLastWordColor: true,
      lastWordColor: '#FF007A'
    }
  },
  {
    id: 'retro-synthwave',
    name: '80s Retro Synthwave',
    scope: 'Retro music, nostalgia, drift cars, synth aesthetic. Neon orange gradient with vivid purple outline.',
    category: 'retro',
    icon: '🌆',
    badge: 'SYNTHWAVE',
    previewBg: '#000000',
    sampleNormal: '80s',
    sampleProminent: 'Synthwave',
    config: {
      templateId: 'retro-synthwave',
      normalFontFamily: 'Righteous',
      prominentFontFamily: 'Righteous',
      fontSize: 32,
      position: 'middle-left',
      textColor: '#FFE600',
      prominentColor: '#FF6B00',
      normalOutlineColor: '#581C87',
      normalOutlineWidth: 3.0,
      prominentOutlineColor: '#581C87',
      prominentOutlineWidth: 3.5,
      shadowColor: 'rgba(255,0,122,0.4)',
      shadowBlur: 12,
      animation: 'anim-neon-pulse',
      uppercase: false,
      karaokeHighlightColor: '#FF6B00',
      enableLastWordColor: true,
      lastWordColor: '#FF007A'
    }
  },
  {
    id: 'typewriter-mystery',
    name: 'Typewriter Mystery',
    scope: 'True crime, unsolved mysteries, conspiracy theories, journaling. Mechanical monospace typewriter reveal.',
    category: 'story',
    icon: '⌨️',
    badge: 'TYPEWRITER',
    previewBg: '#000000',
    sampleNormal: 'secret',
    sampleProminent: 'Terminal',
    config: {
      templateId: 'typewriter-mystery',
      normalFontFamily: 'CourierNew',
      prominentFontFamily: 'CourierNew',
      fontSize: 28,
      position: 'middle-left',
      textColor: '#22C55E',
      prominentColor: '#86EFAC',
      normalOutlineColor: '#000000',
      normalOutlineWidth: 1.5,
      prominentOutlineColor: '#000000',
      prominentOutlineWidth: 2.0,
      shadowColor: 'rgba(0,0,0,0.95)',
      shadowBlur: 8,
      animation: 'anim-typewriter',
      uppercase: false,
      karaokeHighlightColor: '#86EFAC',
      enableLastWordColor: false
    }
  },
  {
    id: 'beast-workout',
    name: 'Beast Gym Motivation',
    scope: 'Bodybuilding, gym motivation, combat sports, discipline. Massive condensed typography with fiery orange accents.',
    category: 'fitness',
    icon: '🦾',
    badge: 'HEAVY IMPACT',
    previewBg: '#000000',
    sampleNormal: 'crush your',
    sampleProminent: 'Limits',
    config: {
      templateId: 'beast-workout',
      normalFontFamily: 'Anton',
      prominentFontFamily: 'Anton',
      fontSize: 38,
      position: 'middle-left',
      textColor: '#FFFFFF',
      prominentColor: '#FF3D00',
      normalOutlineColor: '#000000',
      normalOutlineWidth: 3.5,
      prominentOutlineColor: '#000000',
      prominentOutlineWidth: 4.0,
      shadowColor: 'rgba(0,0,0,0.95)',
      shadowBlur: 10,
      animation: 'anim-zoom-impact',
      uppercase: true,
      karaokeHighlightColor: '#FF3D00',
      enableLastWordColor: true,
      lastWordColor: '#FF3D00'
    }
  },
  {
    id: 'podcast-studio',
    name: 'Podcast Studio Pro',
    scope: 'Long-form podcasts, interview highlights, TED talks. Balanced dual-tone lower-third with maximum clarity.',
    category: 'podcast',
    icon: '🎙️',
    badge: 'STUDIO PODCAST',
    previewBg: '#000000',
    sampleNormal: 'episode',
    sampleProminent: 'Studio Pro',
    config: {
      templateId: 'podcast-studio',
      normalFontFamily: 'Oswald',
      prominentFontFamily: 'Oswald',
      fontSize: 30,
      position: 'middle-left',
      textColor: '#FFFFFF',
      prominentColor: '#FBBF24',
      normalOutlineColor: '#000000',
      normalOutlineWidth: 2.0,
      prominentOutlineColor: '#000000',
      prominentOutlineWidth: 2.5,
      shadowColor: 'rgba(0,0,0,0.9)',
      shadowBlur: 8,
      animation: 'anim-fade',
      uppercase: false,
      karaokeHighlightColor: '#FBBF24',
      enableLastWordColor: true,
      lastWordColor: '#FBBF24'
    }
  },
  {
    id: 'breaking-news',
    name: 'Breaking News Alert',
    scope: 'Current affairs, breaking announcements, journalism, urgent alerts. Heavy headline font with broadcast red accents.',
    category: 'news',
    icon: '🚨',
    badge: 'BREAKING NEWS',
    previewBg: '#000000',
    sampleNormal: 'breaking',
    sampleProminent: 'News Alert',
    config: {
      templateId: 'breaking-news',
      normalFontFamily: 'Arial',
      prominentFontFamily: 'Arial',
      fontSize: 32,
      position: 'middle-left',
      textColor: '#FFFFFF',
      prominentColor: '#EF4444',
      normalOutlineColor: '#000000',
      normalOutlineWidth: 3.0,
      prominentOutlineColor: '#000000',
      prominentOutlineWidth: 3.5,
      shadowColor: 'rgba(0,0,0,0.95)',
      shadowBlur: 10,
      animation: 'anim-elastic-snap',
      uppercase: true,
      karaokeHighlightColor: '#EF4444',
      enableLastWordColor: true,
      lastWordColor: '#EF4444'
    }
  },
  {
    id: 'holographic-dream',
    name: 'Holographic Dream',
    scope: 'Creative art, music videos, dreamcore, futuristic design. Chromatic liquid gradient flow with iridescent shimmer.',
    category: 'creative',
    icon: '🔮',
    badge: 'HOLO CHROMA',
    previewBg: '#000000',
    sampleNormal: 'future',
    sampleProminent: 'Dreams',
    config: {
      templateId: 'holographic-dream',
      normalFontFamily: 'Syne',
      prominentFontFamily: 'Syne',
      fontSize: 32,
      position: 'middle-left',
      textColor: '#E0E7FF',
      prominentColor: '#C084FC',
      normalOutlineColor: '#312E81',
      normalOutlineWidth: 2.5,
      prominentOutlineColor: '#312E81',
      prominentOutlineWidth: 3.0,
      shadowColor: 'rgba(192,132,252,0.4)',
      shadowBlur: 14,
      animation: 'anim-liquid-gradient',
      uppercase: false,
      karaokeHighlightColor: '#C084FC',
      enableLastWordColor: true,
      lastWordColor: '#C084FC'
    }
  },
  {
    id: 'urban-streetwear',
    name: 'Urban Streetwear',
    scope: 'Street fashion, skateboarding, hip-hop, graffiti art. Heavy block letter display with spray yellow accents.',
    category: 'street',
    icon: '🛹',
    badge: 'URBAN STREET',
    previewBg: '#000000',
    sampleNormal: 'exclusive',
    sampleProminent: 'Street Drop',
    config: {
      templateId: 'urban-streetwear',
      normalFontFamily: 'Bungee',
      prominentFontFamily: 'Bungee',
      fontSize: 30,
      position: 'middle-left',
      textColor: '#FFFFFF',
      prominentColor: '#FACC15',
      normalOutlineColor: '#000000',
      normalOutlineWidth: 3.0,
      prominentOutlineColor: '#000000',
      prominentOutlineWidth: 3.5,
      shadowColor: 'rgba(0,0,0,0.95)',
      shadowBlur: 10,
      animation: 'anim-pop',
      uppercase: true,
      karaokeHighlightColor: '#FACC15',
      enableLastWordColor: true,
      lastWordColor: '#FACC15'
    }
  }
];

// Default configuration for Landscape (16:9) - Pre-configured from Template 1 (September Vibrant Pop)
export const DEFAULT_LANDSCAPE_CONFIG = {
  ...CAPTION_TEMPLATES[0].config,
  fontSize: 30,
  maxWordsPerLine: 6,
  progressiveDisplay: true,
  enhanceQuality: true
};

// Default configuration for Portrait (9:16 Shorts/Reels) - Pre-configured from Template 1 (September Vibrant Pop)
export const DEFAULT_PORTRAIT_CONFIG = {
  ...CAPTION_TEMPLATES[0].config,
  fontSize: 34,
  maxWordsPerLine: 5,
  progressiveDisplay: true,
  enhanceQuality: true
};

